/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'color' : string,
  'size' : string,
  'productId' : string,
  'quantity' : bigint,
}
export interface CustomerInfo {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'email' : string,
  'address' : string,
}
export type ExternalBlob = Uint8Array;
export interface FilterOptions {
  'sortBy' : [] | [string],
  'priceRange' : [] | [PriceRange],
  'category' : [] | [string],
  'searchQuery' : [] | [string],
}
export interface Order {
  'id' : string,
  'customerInfo' : CustomerInfo,
  'status' : string,
  'paymentStatus' : string,
  'paymentMethod' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'color' : string,
  'size' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Price { 'currency' : string, 'amount' : bigint }
export interface PriceRange {
  'maxAmount' : bigint,
  'minAmount' : bigint,
  'currency' : string,
}
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'category' : string,
  'colors' : Array<string>,
  'price' : Price,
  'images' : Array<ExternalBlob>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<
    [CustomerInfo, Array<CartItem>, [] | [string]],
    string
  >,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[[] | [FilterOptions]], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCartItemQuantity' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updatePaymentStatus' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'uploadProductImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];